### ISSUE TITLE
UTF-8 (i'm using the 1.0.8-hotfix)

### ISSUE THREAD

**Issue by SOekd** [sim0n/Caesium#10]
obfuscated:
https://prnt.sc/10kq64r
https://prnt.sc/10kq8ce

https://prnt.sc/10kq80e

without obfuscation:
https://prnt.sc/10kqawa

**Comment by sim0n** [comment]
Okay, this *should* hopefully be fixed. Can you test the latest release?

**Comment by SOekd** [comment]
> Okay, this _should_ hopefully be fixed. Can you test the latest release?
It's working!
