### ISSUE TITLE
Section sign "§" breaking messages (Spigot)

### ISSUE THREAD

**Issue by vKekz** [sim0n/Caesium#15]
So somehow "§" is being used, but in a weird way. For instance it is breaking chat and console messages in Spigot (color codes) with adding new unknown chars. I dont know how it is with other UTF-8 chars.

Version: latest (v1.0.9)
Java: 8

Console:
![Screenshot_1](https://user-images.githubusercontent.com/43937246/115970134-d54cc400-a540-11eb-8972-46128dc5fc14.png)

Ingame:
![Screenshot_2](https://user-images.githubusercontent.com/43937246/115970141-e1d11c80-a540-11eb-8cfd-e9a2a6e0b0f3.png)

**Comment by Pixchure** [comment]
I recommend trying to use ChatColor (in Bungeecord api I think). It should work I think
