### ISSUE TITLE
Java 17 rt.jar doesn't exists

### ISSUE THREAD

**Issue by CrAfTsArMy** [sim0n/Caesium#25]
Hey,

I tried to obfuscate my program which is written in java version 17. However, I noticed that the rt.jar does not exist in higher java versions! I already tried to use the src.zip which is in the lib folder, but it doesn't work.

Could you possibly tell me which file I have to add / use so that it works?

Thanks in advance.

**Comment by JonnyOnlineYT** [comment]
Java 9+ Doesnt have a rt.jar
You can get the same effect tho by using the `jrt-fs.jar`

**Comment by CrAfTsArMy** [comment]
Thanks
