### ISSUE TITLE
Suggestion - Log/Precentage of completion

### ISSUE THREAD

**Issue by GreatZardasht** [sim0n/Caesium#3]
Something that tells you how much precent its completed so you know when obfuscated jar would be ready, also something that shows the logs on what class it is currently obfuscating

**Comment by Gowixx** [comment]
@GreatZardasht You can already do this,
all you have to do is run it via the
`java -jar Caesium.jar`
and it logs everything that's happening in the Command Promt Line

**Comment by GreatZardasht** [comment]
ye i noticed when i built it in eclipse xd
